	-- Zombie Parts
	['zombie_brain'] 				 = {['name'] = 'zombie_brain', 			  	  	['label'] = 'Zombie Brain', 				['weight'] = 50, 		['type'] = 'item', 		['image'] = 'zombie_brain.png', 	['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Zombie Brain'},
	['zombie_heart'] 				 = {['name'] = 'zombie_heart', 			  	  	['label'] = 'Zombie Heart', 				['weight'] = 50, 		['type'] = 'item', 		['image'] = 'zombie_heart.png', 	['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Zombie Heart'},
	['zombie_lungs'] 				 = {['name'] = 'zombie_lungs', 			  	  	['label'] = 'Zombie Lungs', 				['weight'] = 100, 		['type'] = 'item', 		['image'] = 'zombie_lungs.png', 	['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Zombie Lungs'},
	['zombie_arm'] 					 = {['name'] = 'zombie_arm', 			  	  	['label'] = 'Zombie Arm', 					['weight'] = 20, 		['type'] = 'item', 		['image'] = 'zombie_arm.png', 		['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Zombie Arm'},
	['zombie_foot'] 				 = {['name'] = 'zombie_foot', 			  	  	['label'] = 'Zombie Foot', 					['weight'] = 20, 		['type'] = 'item', 		['image'] = 'zombie_foot.png', 		['unique'] = false, 	['useable'] = false, 	['shouldClose'] = true,   ['combinable'] = nil,   ['description'] = 'Zombie Foot'},

	-- Evidence
	["evidence_briefcase"] 			 = {["name"] = "evidence_briefcase", 			["label"] = "Briefcase", 				 ["weight"] = 400, 		 ["type"] = "item", 	 ["image"] = "evidence_briefcase.png", 			 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "This briefcase may contain valuable evidence."},
	["evidence_documents"] 			 = {["name"] = "evidence_documents", 			["label"] = "Zombie Documents", 		 ["weight"] = 400, 		 ["type"] = "item", 	 ["image"] = "evidence_documents.png", 			 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "These documents appear to show people in various stages of the disease."},
	["evidence_notes"] 			 	 = {["name"] = "evidence_notes",				["label"] = "Zombie Notes", 		 	 ["weight"] = 400, 		 ["type"] = "item", 	 ["image"] = "evidence_notes.png", 				 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "Strange notes with zombie diagrams and sketches of weird molecules."},
	["evidence_samples"] 			 = {["name"] = "evidence_samples",				["label"] = "Zombie Samples", 		 	 ["weight"] = 400, 		 ["type"] = "item", 	 ["image"] = "evidence_samples.png", 			 ["unique"] = false, 	["useable"] = true, 	["shouldClose"] = true,	   ["combinable"] = nil,   ["description"] = "These vials contain samples of the Z Virus for analysis."},
	['evidence_usb'] 				 = {['name'] = 'evidence_usb', 			  	  	['label'] = 'Zombie Data USB', 			 ['weight'] = 0, 		 ['type'] = 'item', 	 ['image'] = 'usb_device.png', 					 ['unique'] = false, 	['useable'] = true, 	['shouldClose'] = true,	   ['combinable'] = nil,   ['description'] = 'This flash drive has pictures, hidden videos and important data files.'},
